#### Sorting, Ranking & Basic Statistical Operations

In this we learn about sorting , ranking and basic statistical operations using pandas

In [1]:
import numpy as np
import pandas as pd

why sorting?
sorting helps us to reorder the data to reveal the patterns that are not visible in raw order

In [2]:
df_store = pd.read_csv('../datasets/superstore_excel.csv')
df_store

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers,Virtual didactic synergy,2467.49,9,0.29,617.24
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings,Operative reciprocal projection,2751.66,1,0.09,922.14
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs,Multi-lateral incremental knowledge user,1199.66,9,0.03,220.44
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels,Integrated bifurcated groupware,2335.57,6,0.30,620.16
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders,Re-contextualized human-resource benchmark,2540.88,5,0.03,258.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,CA-780853,2025-03-04,2025-04-13,Second Class,CUST-8307,Adam Scott,Home Office,West,Office Supplies,Art,Polarized 3rdgeneration frame,3322.63,4,0.37,-14.44
4996,CA-489090,2023-06-20,2025-04-28,Same Day,CUST-1311,Kathryn Miller,Home Office,South,Furniture,Chairs,Enhanced contextually-based focus group,4518.10,1,0.37,561.98
4997,CA-203624,2024-03-11,2025-04-23,Standard Class,CUST-6014,Tiffany Moreno,Corporate,East,Technology,Accessories,Fundamental human-resource capacity,4631.15,4,0.47,356.98
4998,CA-562734,2024-11-04,2025-04-20,Same Day,CUST-1274,Yolanda Conner,Corporate,West,Furniture,Chairs,Optimized holistic approach,1691.66,3,0.35,462.50
4999,CA-852804,2024-03-22,2025-04-24,First Class,CUST-6238,Michael Giles,Home Office,East,Furniture,Chairs,Team-oriented 4thgeneration task-force,4450.05,8,0.00,-4.91

we can sort sales row and then we can analyze ut to get the patterns

to sort the data set using values inside them we can use `df.sort_values(by,asc,inplace)`

In [3]:
df_store.sort_values(by='Sales', ascending=False)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4135,CA-846185,2023-07-06,2025-04-21,Standard Class,CUST-4079,Gary Wise,Consumer,West,Office Supplies,Labels,Self-enabling homogeneous hierarchy,4997.57,1,0.37,339.64
4930,CA-238428,2024-03-08,2025-04-15,First Class,CUST-6915,Samuel Taylor,Corporate,East,Furniture,Chairs,Synergized human-resource matrices,4996.78,1,0.49,-91.36
2125,CA-254261,2023-05-04,2025-04-15,First Class,CUST-5374,Matthew Singleton,Home Office,Central,Furniture,Bookcases,User-friendly 4thgeneration system engine,4995.27,8,0.41,92.44
92,CA-611227,2024-08-25,2025-04-12,First Class,CUST-8181,Mr. John Walker,Corporate,East,Furniture,Chairs,Organized didactic core,4994.60,8,0.17,327.75
2222,CA-338459,2024-04-09,2025-05-03,Same Day,CUST-5109,Madison Cook,Corporate,West,Office Supplies,Labels,Managed object-oriented adapter,4994.52,9,0.45,11.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106,CA-709860,2023-05-22,2025-04-16,Same Day,CUST-7503,Maria Mayo,Home Office,Central,Office Supplies,Storage,Multi-channeled bandwidth-monitored installation,10.08,10,0.15,102.87
4934,CA-193512,2024-07-30,2025-04-19,Same Day,CUST-3075,Rhonda Scott,Consumer,West,Office Supplies,Paper,Extended directional utilization,8.80,2,0.13,467.46
4480,CA-507779,2024-05-10,2025-04-25,First Class,CUST-2607,Natalie Black,Consumer,South,Technology,Phones,Integrated attitude-oriented model,7.76,9,0.43,111.11
1424,CA-554925,2024-01-15,2025-05-02,Second Class,CUST-8861,Carrie Roberts,Consumer,West,Furniture,Furnishings,Self-enabling bi-directional synergy,7.54,3,0.50,14.81
2761,CA-594934,2023-10-19,2025-05-06,First Class,CUST-1558,Michael Walker,Consumer,West,Technology,Accessories,Intuitive 6thgeneration support,7.37,4,0.15,405.61

In [4]:
df_store.sort_values(by='Profit',ascending=False)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4620,CA-740217,2023-09-24,2025-05-03,Same Day,CUST-6051,Barry Landry,Consumer,West,Furniture,Furnishings,Universal global infrastructure,30.97,9,0.27,999.77
3988,CA-784892,2024-04-01,2025-04-24,First Class,CUST-7265,Hector Bradford,Home Office,West,Technology,Machines,Enterprise-wide multi-tasking policy,1808.76,1,0.04,999.00
142,CA-439054,2025-01-22,2025-04-17,Standard Class,CUST-5706,William Dalton,Consumer,South,Furniture,Tables,Monitored tertiary framework,3729.52,7,0.49,998.84
4916,CA-916138,2023-06-22,2025-04-20,Standard Class,CUST-8544,Anthony Hill,Consumer,Central,Technology,Machines,Multi-layered local approach,806.88,8,0.12,998.09
3681,CA-306307,2023-07-25,2025-04-22,First Class,CUST-8978,Dwayne Gonzalez,Consumer,East,Technology,Computers,Stand-alone zero administration analyzer,969.02,5,0.17,997.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,CA-939132,2023-06-21,2025-04-20,Same Day,CUST-6110,Nichole Foster,Home Office,West,Office Supplies,Art,Business-focused local structure,1524.31,1,0.17,-99.69
1729,CA-869460,2024-03-07,2025-04-28,First Class,CUST-7577,Michelle Herrera,Corporate,East,Technology,Phones,Synergized composite secured line,41.25,2,0.10,-99.85
1007,CA-445975,2024-12-04,2025-05-04,Same Day,CUST-1001,Susan Bell,Home Office,Central,Technology,Computers,Progressive empowering alliance,716.24,9,0.26,-99.86
3755,CA-391036,2023-05-15,2025-04-20,First Class,CUST-9228,Destiny Munoz,Consumer,East,Technology,Phones,Quality-focused 3rdgeneration budgetary manage...,4577.46,4,0.09,-99.92
80,CA-747599,2023-10-27,2025-04-30,Standard Class,CUST-8262,Ronald Brown,Corporate,Central,Office Supplies,Paper,Managed impactful budgetary management,3496.66,6,0.42,-99.96

In [5]:
df_store.sort_values(by=['Region','Profit'],ascending=False)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4620,CA-740217,2023-09-24,2025-05-03,Same Day,CUST-6051,Barry Landry,Consumer,West,Furniture,Furnishings,Universal global infrastructure,30.97,9,0.27,999.77
3988,CA-784892,2024-04-01,2025-04-24,First Class,CUST-7265,Hector Bradford,Home Office,West,Technology,Machines,Enterprise-wide multi-tasking policy,1808.76,1,0.04,999.00
1334,CA-199410,2024-07-12,2025-04-16,Same Day,CUST-2494,John Williams,Consumer,West,Furniture,Furnishings,Vision-oriented demand-driven core,1584.92,9,0.33,997.87
303,CA-576459,2024-09-13,2025-04-30,Second Class,CUST-3951,Amanda Acevedo,Home Office,West,Technology,Copiers,Ergonomic background model,2170.21,9,0.31,997.56
3728,CA-298264,2024-04-29,2025-05-04,Second Class,CUST-5516,William Walker,Consumer,West,Technology,Phones,Upgradable modular open system,1925.72,4,0.43,997.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,CA-203787,2024-06-14,2025-04-12,Second Class,CUST-8538,Robert Jones,Consumer,Central,Technology,Phones,Cross-group disintermediate collaboration,2045.98,3,0.26,-95.09
381,CA-173707,2025-02-12,2025-04-11,Standard Class,CUST-8922,Alexander Henry,Home Office,Central,Office Supplies,Labels,User-centric tangible portal,4031.38,9,0.26,-95.98
409,CA-541329,2023-04-22,2025-04-25,Second Class,CUST-7815,Nicholas Jones,Consumer,Central,Office Supplies,Paper,Realigned maximized array,4193.94,3,0.40,-99.01
1007,CA-445975,2024-12-04,2025-05-04,Same Day,CUST-1001,Susan Bell,Home Office,Central,Technology,Computers,Progressive empowering alliance,716.24,9,0.26,-99.86
80,CA-747599,2023-10-27,2025-04-30,Standard Class,CUST-8262,Ronald Brown,Corporate,Central,Office Supplies,Paper,Managed impactful budgetary management,3496.66,6,0.42,-99.96

To check the random data we can use `df.sample(num)`

In [6]:
df_store.sample(7)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2171,CA-410335,2025-03-04,2025-04-18,First Class,CUST-2533,Jordan Kaiser,Corporate,West,Office Supplies,Paper,De-engineered 24/7 frame,1601.88,10,0.24,541.50
1169,CA-530476,2025-01-03,2025-04-18,Same Day,CUST-8076,Stephanie Watson,Corporate,South,Furniture,Furnishings,Automated context-sensitive parallelism,3779.80,2,0.26,500.33
3071,CA-800321,2024-07-16,2025-04-11,Same Day,CUST-2159,Matthew Hart,Corporate,South,Furniture,Bookcases,Customizable global help-desk,4613.62,7,0.47,373.00
3444,CA-129148,2024-09-07,2025-04-26,First Class,CUST-8601,Noah Jimenez,Home Office,West,Office Supplies,Art,Configurable grid-enabled workforce,1493.76,8,0.25,291.83
2333,CA-319869,2023-04-11,2025-04-20,First Class,CUST-2688,Nathan Norris,Home Office,West,Furniture,Furnishings,Stand-alone leadingedge project,4202.96,6,0.11,-23.34
2487,CA-688049,2023-12-12,2025-05-06,Same Day,CUST-2863,Erika Campbell,Home Office,South,Technology,Phones,Optional fault-tolerant Graphic Interface,546.67,5,0.31,945.11
784,CA-549246,2023-09-16,2025-05-04,First Class,CUST-6192,William Lopez,Consumer,South,Office Supplies,Binders,Re-contextualized cohesive Internet solution,4428.24,10,0.12,262.18

In [7]:
df_store.sort_index(axis=1,ascending=False)

,Sub-Category,Ship Mode,Ship Date,Segment,Sales,Region,Quantity,Profit,Product Name,Order ID,Order Date,Discount,Customer Name,Customer ID,Category
0,Copiers,Second Class,2025-05-01,Home Office,2467.49,South,9,617.24,Virtual didactic synergy,CA-198797,2024-10-06,0.29,Ruben Ramirez,CUST-4170,Technology
1,Furnishings,First Class,2025-05-05,Home Office,2751.66,Central,1,922.14,Operative reciprocal projection,CA-233440,2023-06-12,0.09,Jesse Ortega,CUST-1196,Furniture
2,Chairs,Standard Class,2025-04-24,Corporate,1199.66,East,9,220.44,Multi-lateral incremental knowledge user,CA-691533,2024-04-18,0.03,Kathryn Castro,CUST-2985,Furniture
3,Labels,First Class,2025-05-07,Consumer,2335.57,South,6,620.16,Integrated bifurcated groupware,CA-277218,2023-11-02,0.30,Sharon Taylor,CUST-2412,Office Supplies
4,Binders,First Class,2025-04-14,Corporate,2540.88,South,5,258.06,Re-contextualized human-resource benchmark,CA-311967,2023-07-15,0.03,David Murillo,CUST-3728,Office Supplies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Art,Second Class,2025-04-13,Home Office,3322.63,West,4,-14.44,Polarized 3rdgeneration frame,CA-780853,2025-03-04,0.37,Adam Scott,CUST-8307,Office Supplies
4996,Chairs,Same Day,2025-04-28,Home Office,4518.10,South,1,561.98,Enhanced contextually-based focus group,CA-489090,2023-06-20,0.37,Kathryn Miller,CUST-1311,Furniture
4997,Accessories,Standard Class,2025-04-23,Corporate,4631.15,East,4,356.98,Fundamental human-resource capacity,CA-203624,2024-03-11,0.47,Tiffany Moreno,CUST-6014,Technology
4998,Chairs,Same Day,2025-04-20,Corporate,1691.66,West,3,462.50,Optimized holistic approach,CA-562734,2024-11-04,0.35,Yolanda Conner,CUST-1274,Furniture
4999,Chairs,First Class,2025-04-24,Home Office,4450.05,East,8,-4.91,Team-oriented 4thgeneration task-force,CA-852804,2024-03-22,0.00,Michael Giles,CUST-6238,Furniture

Ranking can just assign position numbers, It can't move the data

In [8]:
df_store.rank()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,559.0,3718.0,3785.5,3114.0,1780.5,4093.0,4159.0,3105.0,4169.5,2349.0,4855.0,2483.0,4236.0,2895.0,3242.0
1,748.0,420.5,4418.5,608.5,107.0,2134.0,4159.0,623.5,835.5,2734.0,2668.0,2781.0,258.0,899.0,4629.5
2,3271.0,2540.0,2565.5,4383.5,1129.0,2602.0,2474.5,1854.0,835.5,1632.0,2313.0,1172.0,4236.0,298.5,1455.5
3,974.0,1416.5,4757.0,608.5,792.5,4340.0,816.0,3105.0,2504.5,3116.0,1945.0,2361.0,2729.0,3007.5,3255.0
4,1189.0,647.5,884.0,608.5,1542.0,1177.0,2474.5,3105.0,2504.5,833.5,3506.0,2558.0,2255.0,298.5,1637.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,3787.0,4744.5,714.0,3114.0,4071.0,30.5,4159.0,4374.5,2504.5,500.0,3016.0,3337.0,1766.5,3696.0,395.0
4996,2138.0,477.0,3268.5,1839.0,162.0,2604.0,4159.0,3105.0,835.5,1632.0,1087.0,4554.0,258.0,3696.0,3013.0
4997,585.0,2286.5,2398.5,4383.5,2837.0,4708.0,2474.5,1854.0,4169.5,173.0,1666.0,4661.0,1766.5,4712.5,2104.0
4998,2554.0,3910.0,1907.0,1839.0,145.0,4976.0,2474.5,4374.5,835.5,1632.0,2689.0,1675.0,1275.0,3499.5,2576.0
4999,4189.0,2363.5,2565.5,608.5,2964.0,3367.0,4159.0,1854.0,835.5,1632.0,4369.0,4472.0,3736.0,26.5,450.5

rank provides the rank for the values it appear in the data set see the below example 

to use rank method syntax - `df.rank()`

In [9]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

we can give some methods so we can get the integer ranks

In [11]:
obj.rank(method='first')#which appears first gets first rank

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [15]:
obj.rank(method='first',ascending=False)

0    1.0
1    7.0
2    2.0
3    3.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [17]:
df_store.rank().sort_values(by='Sales')

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2761,2723.0,1314.5,4589.5,608.5,308.5,3444.5,816.0,4374.5,4169.5,173.0,1998.0,1.0,1766.5,1482.5,2330.0
1424,2494.0,1923.0,3955.0,3114.0,4355.0,764.0,816.0,4374.5,835.5,2734.0,3968.0,2.0,1275.0,4977.0,534.0
4480,2246.0,2710.5,2735.5,608.5,912.0,3642.0,816.0,3105.0,4169.5,4101.0,1943.0,3.0,4236.0,4318.5,990.0
4934,525.0,3272.5,1737.0,1839.0,1172.5,3950.0,816.0,4374.5,2504.5,3764.5,1323.0,4.0,773.0,1292.0,2599.0
1106,3376.0,285.0,1219.0,1839.0,3656.0,3105.0,4159.0,623.5,2504.5,4426.5,2248.0,5.0,4744.5,1482.5,948.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2222,1348.0,2478.5,4111.5,1839.0,2300.0,3065.0,2474.5,4374.5,2504.5,3116.0,2124.0,4996.0,4236.0,4511.0,516.0
92,2814.0,3442.5,549.5,608.5,4003.5,3583.0,2474.5,1854.0,835.5,1632.0,2828.0,4997.0,3736.0,1672.0,1982.0
2125,858.0,164.5,1051.0,608.5,2449.0,3247.0,4159.0,623.5,835.5,1210.5,4745.0,4998.0,3736.0,4095.5,899.0
4930,771.0,2266.5,1051.0,608.5,3336.0,4178.0,2474.5,1854.0,835.5,1632.0,4342.0,4999.0,258.0,4910.0,35.0
4135,4151.0,593.5,2071.5,4383.5,1728.0,1630.0,816.0,4374.5,2504.5,3116.0,3988.0,5000.0,258.0,3696.0,2037.0

In [18]:
df_store.rank().sort_values(by='Profit')

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
80,3598.0,1361.5,3614.0,4383.5,4050.0,4078.0,2474.5,623.5,2504.5,3764.5,2110.0,3504.0,2729.0,4209.0,1.0
3755,1642.0,236.0,1907.0,608.5,4577.0,1282.0,816.0,1854.0,4169.5,4101.0,3436.0,4613.0,1766.5,899.0,2.0
1007,1928.0,4116.0,4262.5,1839.0,2.0,4521.0,4159.0,623.5,4169.5,2012.0,3349.0,678.0,4236.0,2602.0,3.0
1729,4287.0,2254.0,3268.5,608.5,3691.0,3488.0,2474.5,1854.0,4169.5,4101.0,4329.0,24.0,773.0,996.0,4.0
42,4670.0,485.5,1907.0,1839.0,2895.0,3696.0,4159.0,4374.5,2504.5,500.0,321.0,1498.0,258.0,1672.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3681,1153.0,715.5,2233.0,608.5,4432.0,1412.0,816.0,1854.0,4169.5,2012.0,4110.0,924.0,2255.0,1672.0,4996.0
4916,4566.0,493.0,1907.0,4383.5,4174.0,394.0,816.0,623.5,4169.5,3445.5,2358.0,762.0,3736.0,1200.0,4997.0
142,1899.0,4470.5,1384.0,4383.5,2651.5,4940.0,816.0,3105.0,835.5,4791.5,2234.0,3747.0,3225.0,4910.0,4998.0
3988,3807.0,2427.0,2565.5,608.5,3529.0,1749.0,4159.0,4374.5,4169.5,3445.5,1159.0,1811.0,258.0,401.5,4999.0
4620,3549.0,1145.0,4111.5,1839.0,2858.5,486.0,816.0,4374.5,835.5,2734.0,4549.0,18.0,4236.0,2700.0,5000.0

In [19]:
df_store.describe()

             Sales     Quantity     Discount       Profit
count  5000.000000  5000.000000  5000.000000  5000.000000
mean   2501.363102     5.501400     0.250084   447.942226
std    1424.757879     2.897737     0.144133   318.285948
min       7.370000     1.000000     0.000000   -99.960000
25%    1275.347500     3.000000     0.130000   174.525000
50%    2482.830000     6.000000     0.250000   444.955000
75%    3733.710000     8.000000     0.380000   725.157500
max    4997.570000    10.000000     0.500000   999.770000